### ISSUE TITLE
美區App Store無法下載

### ISSUE THREAD

**Issue by ming1644** [WishCanTaiwan/VocabuLazy-iOS#28]
話說, 怎麼找不到可以跟開發團隊聯繫的方式, 要反映意見都不知道去哪?
美區App Store找不到, 請團隊確認一下? 是否只限制台灣App Store下載?

**Comment by JerryZGY** [comment]
你好，目前 App Store 僅開放台灣下載哦
由於目前還有其他需要優先處理的問題，我們會盡快在日後開放其他區域下載
意見或問題回報歡迎直接至[VocabuLazy粉絲專頁](https://www.facebook.com/vocabulazy/)反應
可以得到比較快的答覆，謝謝你的支持～
